services:
  build:
    environment:
      HOSTUID: ${HOSTUID}
      HOSTGID: ${HOSTGID}
      VERSION: ${VERSION}
    image: ${REGISTRY_IMAGE}:${TAG}
    platform: ${PLATFORM:-linux/amd64}
    volumes:
      - $PWD:$WORKSPACE
    working_dir: $WORKSPACE
    command: $SCRIPT
